### Site Settings ###
title               : Prudhvi Raj Belide
description         : >-
                      Embedded Software Student | Projects, Skills & Portfolio
baseurl             : ""                                # keep empty if repo is <username>.github.io
repository          : https://prudhvibelide.github.io/
remote_theme        : 
open_new_tab        : true                              # external links open in new tab


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # exclude these pages from navbar
  - pages/tags.html
  - pages/404.html


### Author Info ###
author:
  name              : Prudhvi Raj Belide
  image             : assets/img/profile.jpg            # place your own image here
  email             : your@email.com
  github            : prudhvi-b007
  linkedin          : your-linkedin-username
  twitter           : your-twitter-handle
# Add/remove other social links as needed


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus (optional for blog comments) ###
disqus:
  shortname: ""


### Analytics (optional) ###
analytics:
  enabled: false
  google:
    tracking_id: ""


### Buy me a coffee (optional) ###
buymeacoffee:
  enabled: false
  username: ""
  color: "#007bff"
  message: "Thank you for visiting."
 

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
  - test/
  - docs/

