title: Prudhvi's Portfolio
description: Curious Embedded Engineer
baseurl: ""                      # user site needs empty
repository: prudhvibelide/prudhvibelide.github.io
open_new_tab: true

plugins: [jemoji]

nav_exclude:
  - pages/404.html
  - pages/index.md
  - docs/**
  - elements/**

author:
  name: Prudhvi Raj Belide
  image: assets/img/profile.jpg
  github: prudhvibelide
  linkedin: prudhvibelide10

permalink: /blog/:title

collections:
  projects:
    output: true
    permalink: /projects/:name

exclude:
  - README.md
  - LICENSE
  - "*.log"
  - docs/
  - test/
